db:
  image: million12/mariadb:latest
  ports:
    - 3306
  environment:
    MARIADB_PASS: secret-db-password-qpu34thqrgaR3

web:
  image: million12/typo3-neos
  ports:
    - '8080:80'
  links:
    - db:db
  environment:
    T3APP_VHOST_NAMES: neos dev.neos behat.dev.neos
    T3APP_NEOS_SITE_PACKAGE: Neos.Demo

#dev:
#  image: million12/php-app-ssh
#  ports:
#    - '1122:22'
#  links:
#    - db:db
#    - web:web
#  volumes_from:
#    - web
#  environment:
#    IMPORT_GITHUB_PUB_KEYS: github,user,names,here
